In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:

### sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]


In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
##define the vocabulary size
voc_size = 10000

In [ ]:
### sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]


In [6]:
##one hot representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[6219, 9166, 7060, 5165],
 [6219, 9166, 7060, 682],
 [6219, 7014, 7060, 2861],
 [8849, 5156, 3374, 1110, 2594],
 [8849, 5156, 3374, 1110, 3688],
 [4137, 6219, 8333, 7060, 8790],
 [4620, 8324, 7375, 1110]]

In [8]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [9]:
import numpy as np

In [11]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6219 9166 7060 5165]
 [   0    0    0    0 6219 9166 7060  682]
 [   0    0    0    0 6219 7014 7060 2861]
 [   0    0    0 8849 5156 3374 1110 2594]
 [   0    0    0 8849 5156 3374 1110 3688]
 [   0    0    0 4137 6219 8333 7060 8790]
 [   0    0    0    0 4620 8324 7375 1110]]


In [ ]:
'''sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)'''

[[6219 9166 7060 5165    0    0    0    0]
 [6219 9166 7060  682    0    0    0    0]
 [6219 7014 7060 2861    0    0    0    0]
 [8849 5156 3374 1110 2594    0    0    0]
 [8849 5156 3374 1110 3688    0    0    0]
 [4137 6219 8333 7060 8790    0    0    0]
 [4620 8324 7375 1110    0    0    0    0]]


In [13]:
#feature representation
dim=10

In [17]:
model= Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [18]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 199ms/step


array([[[-0.03717259,  0.04749364,  0.00132615, -0.00721669,
         -0.00158138, -0.02271842,  0.00365385, -0.03471528,
         -0.02055486, -0.0423488 ],
        [ 0.03838391, -0.0109755 , -0.02160977, -0.04895252,
         -0.04406274, -0.03424908,  0.02565357, -0.00612893,
         -0.04348662, -0.02359881],
        [-0.04690968,  0.00392998, -0.04579364,  0.02168268,
          0.03620822,  0.01818767,  0.0247141 , -0.00127666,
         -0.04512921,  0.03454849],
        [ 0.0114128 , -0.0003315 ,  0.01189598, -0.00604622,
         -0.00626953,  0.03781298, -0.01561441,  0.04993793,
         -0.03346767, -0.02273822],
        [-0.00085068, -0.03744649,  0.03415832, -0.04000065,
          0.04946617, -0.01348579, -0.02412645,  0.04732617,
         -0.03296658,  0.01897223],
        [-0.00085068, -0.03744649,  0.03415832, -0.04000065,
          0.04946617, -0.01348579, -0.02412645,  0.04732617,
         -0.03296658,  0.01897223],
        [-0.00085068, -0.03744649,  0.03415832, -0.0

In [20]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 40ms/step


array([[-0.03717259,  0.04749364,  0.00132615, -0.00721669, -0.00158138,
        -0.02271842,  0.00365385, -0.03471528, -0.02055486, -0.0423488 ],
       [ 0.03838391, -0.0109755 , -0.02160977, -0.04895252, -0.04406274,
        -0.03424908,  0.02565357, -0.00612893, -0.04348662, -0.02359881],
       [-0.04690968,  0.00392998, -0.04579364,  0.02168268,  0.03620822,
         0.01818767,  0.0247141 , -0.00127666, -0.04512921,  0.03454849],
       [ 0.0114128 , -0.0003315 ,  0.01189598, -0.00604622, -0.00626953,
         0.03781298, -0.01561441,  0.04993793, -0.03346767, -0.02273822],
       [-0.00085068, -0.03744649,  0.03415832, -0.04000065,  0.04946617,
        -0.01348579, -0.02412645,  0.04732617, -0.03296658,  0.01897223],
       [-0.00085068, -0.03744649,  0.03415832, -0.04000065,  0.04946617,
        -0.01348579, -0.02412645,  0.04732617, -0.03296658,  0.01897223],
       [-0.00085068, -0.03744649,  0.03415832, -0.04000065,  0.04946617,
        -0.01348579, -0.02412645,  0.04732617